spring:
  application:
    name: PRODUCT-DETAIL-SERVICE

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaltuZone: https://localhost:8761/eureka
  
  instance:
      hostname: localhost