version : '3'

services:
  dbservice : 
    image :  mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USERNAME=root
    
    volumes:
      - ./data:/var/lib/mysql

    ports:
      - 3306:3306
    networks:
      - bootapp

  appservice:
    build: ./doc
    depends_on:
      - dbservice
    environment:
      - spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
      - spring.datasource.url = jdbc:mysql://docker-mysql:3306/database?autoReconnect=true&useSSL=false
      - spring.datasource.username = root
      - spring.datasource.password = root
      - spring.jpa.show-sql = true
      - spring.jpa.hibernate.ddl-auto = update
      - spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQL5Dialect
    
    ports:
      - 9000:9000
    networks:
      - bootapp

networks:
  bootapp: