spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user/**

        - id: ADMIN-SERVICE
          uri: lb://ADMIN-SERVICE
          predicates:
            - Path=/admin/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaltuZone: https://localhost:8761/eureka
  
  instance:
      hostname: localhost